// Generated by 'unplugin-auto-import'
export {}
declare global {
  const request: typeof import('~/utils/request')['default']
  const useAppStore: typeof import('./stores/AppStore')['useAppStore']
  const useI18n: typeof import('vue-i18n-bridge')['useI18n']
  const useRoute: typeof import('vue-router/composables')['useRoute']
  const useRouter: typeof import('vue-router/composables')['useRouter']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly request: UnwrapRef<typeof import('~/utils/request')['default']>
    readonly useAppStore: UnwrapRef<typeof import('./stores/AppStore')['useAppStore']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n-bridge')['useI18n']>
    readonly useRoute: UnwrapRef<typeof import('vue-router/composables')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router/composables')['useRouter']>
  }
}
